#!/usr/bin/env node
/**
 * GeoJSON道路データ → ダイコメ用 roads-<region>.js 変換
 *
 * 入力: osmium export で生成された GeoJSON FeatureCollection
 * 出力: window.ROADS_<REGION> 形式のJSファイル
 *
 * 圧縮戦略:
 *  - 座標は1e6倍した整数（精度約11cm・十分）
 *  - 各道路の最初の点のみ絶対値、以降はデルタ
 *  - デルタは概ね小さい数なのでJSON文字列でも十分小さい
 *  - 1km四方グリッドで空間インデックス
 *
 * 使い方: node build-roads.js input.geojson output.js region_name
 */

const fs = require('fs');
const path = require('path');

const [, , INPUT, OUTPUT, REGION] = process.argv;

if (!INPUT || !OUTPUT || !REGION) {
  console.error('Usage: build-roads.js <input.geojson> <output.js> <region>');
  process.exit(1);
}

console.log(`  → 入力: ${INPUT}`);
const raw = fs.readFileSync(INPUT, 'utf8');
const geo = JSON.parse(raw);

if (!geo.features) {
  throw new Error('Invalid GeoJSON: features not found');
}

// 1. 道路抽出（LineString のみ）
const roads = [];
let bbox = [Infinity, Infinity, -Infinity, -Infinity]; // [minLat, minLon, maxLat, maxLon]

for (const f of geo.features) {
  if (!f.geometry) continue;
  const g = f.geometry;
  // LineString or MultiLineString
  const lines = g.type === 'LineString' ? [g.coordinates]
              : g.type === 'MultiLineString' ? g.coordinates
              : null;
  if (!lines) continue;

  for (const coords of lines) {
    if (coords.length < 2) continue;

    // GeoJSON は [lon, lat] 順なので [lat, lon] に並び替えて1e6倍
    const encoded = [];
    let prevLat = null, prevLon = null;
    for (const [lon, lat] of coords) {
      const ilat = Math.round(lat * 1e6);
      const ilon = Math.round(lon * 1e6);
      if (prevLat === null) {
        encoded.push(ilat, ilon); // 絶対値
      } else {
        encoded.push(ilat - prevLat, ilon - prevLon); // デルタ
      }
      prevLat = ilat;
      prevLon = ilon;
      // bbox更新
      if (lat < bbox[0]) bbox[0] = lat;
      if (lon < bbox[1]) bbox[1] = lon;
      if (lat > bbox[2]) bbox[2] = lat;
      if (lon > bbox[3]) bbox[3] = lon;
    }

    const props = f.properties || {};
    const highway = props.highway || '';

    roads.push({
      h: highway,           // 道路種別
      n: props.name || '',  // 名称（空なら空文字）
      c: encoded            // 圧縮済み座標
    });
  }
}

console.log(`  → 道路数: ${roads.length}`);
console.log(`  → bbox: ${bbox.map(v => v.toFixed(4)).join(', ')}`);

// 2. グリッドインデックス（0.01度 ≈ 1km四方）
const GRID = 0.01;
const grid = {};
roads.forEach((r, idx) => {
  // 道路の最初の点のグリッドセルに登録（簡易版・複数セルにまたがる場合は③で対応）
  const lat = r.c[0] / 1e6;
  const lon = r.c[1] / 1e6;
  const gy = Math.floor(lat / GRID);
  const gx = Math.floor(lon / GRID);
  const key = `${gy}_${gx}`;
  (grid[key] ||= []).push(idx);
});

console.log(`  → グリッドセル数: ${Object.keys(grid).length}`);

// 3. JSファイル生成
const REGION_UPPER = REGION.toUpperCase().replace(/-/g, '_');
const out = `// Auto-generated by .github/workflows/osm-update.yml
// Source: Geofabrik ${REGION}-latest.osm.pbf
// Generated: ${new Date().toISOString()}
// DO NOT EDIT MANUALLY
window.ROADS_${REGION_UPPER} = ${JSON.stringify({
  region: REGION,
  generated: new Date().toISOString(),
  bbox: bbox.map(v => Math.round(v * 1e6)),
  gridSize: GRID,
  grid,
  roads
})};
`;

fs.writeFileSync(OUTPUT, out);
const size = fs.statSync(OUTPUT).size;
console.log(`  → 出力サイズ: ${(size / 1024 / 1024).toFixed(2)} MB`);
console.log(`✅ ${OUTPUT} 生成完了`);
